{% set name = "dsf" %}
{% set version = "0.0.34" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dsf-{{ version }}.tar.gz
  sha256: 75a10e38b1f8c80013cd93c6e6e61fcfdca53ce70de57d4707bf7370b6b95d84

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - wheel
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - pandas >=1.5
    - numpy >=1.21

test:
  imports:
    - dsf
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/dsf/
  summary: The dsf package provides a collection of datasets used in the book Data Science Foundations and Machine Learning with Python.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - vanraak
